# Generated by Django 4.2.1 on 2023-06-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordered_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered_product',
            name='customer',
        ),
    ]
