# Generated by Django 4.2.1 on 2023-06-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mode_of_payment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
