# Generated by Django 4.2.1 on 2023-06-11 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_variation_price_alter_variation_stock'),
        ('orders', '0006_order_mode_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered_product',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.variation'),
        ),
    ]
