# Generated by Django 4.2.1 on 2023-06-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_status_ordered_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
