# Generated by Django 4.2.1 on 2023-06-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_returned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returned',
            old_name='extra_notes',
            new_name='comments',
        ),
    ]
