# Generated by Django 4.2.1 on 2023-06-20 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_coupons_valid_till_coupons_is_expired_and_more'),
        ('orders', '0011_rename_extra_notes_returned_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Used_Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.coupons')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
