# Generated by Django 4.2.1 on 2023-12-02 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shooop', max_length=40)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('image', models.FileField(blank=True, upload_to='photos/brands')),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount', models.IntegerField(default=100)),
                ('is_expired', models.BooleanField(default=False)),
                ('minimum_price', models.BigIntegerField(default=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Occassion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual', models.CharField(default='Casuals', max_length=50)),
                ('Formal', models.CharField(default='Formals', max_length=50)),
                ('Sports', models.CharField(default='Sports', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('descr', models.CharField(max_length=550)),
                ('discount', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=40)),
                ('size', models.IntegerField()),
                ('occassion', models.CharField(max_length=40)),
                ('ideal_for', models.CharField(max_length=40)),
                ('descr', models.CharField(blank=True, max_length=400)),
                ('image', models.FileField(blank=True, upload_to='photos/products')),
                ('stock', models.IntegerField(blank=True)),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.coupons')),
                ('offers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.offers')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(blank=True, null=True)),
                ('stock', models.BigIntegerField(blank=True, default=0)),
                ('price', models.BigIntegerField(default=3000)),
                ('discounted_price', models.BigIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
