# Generated by Django 4.2.1 on 2023-05-21 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('discount', models.IntegerField()),
                ('valid_till', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=50)),
                ('discount', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('size', models.IntegerField()),
                ('occassion', models.CharField(max_length=40)),
                ('ideal_for', models.CharField(max_length=40)),
                ('descr', models.CharField(blank=True, max_length=400)),
                ('image', models.ImageField(blank=True, upload_to='photos/products')),
                ('stock', models.IntegerField(blank=True)),
                ('price', models.IntegerField()),
                ('coupon', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.coupons')),
                ('offers', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.offers')),
            ],
        ),
    ]
