# Generated by Django 4.2.1 on 2023-05-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_coupon_alter_products_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(blank=True, upload_to='photos/products'),
        ),
    ]
