# Generated by Django 4.2.1 on 2023-06-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_offers_name_alter_coupons_code_alter_offers_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.BigIntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='variation',
            name='stock',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
