# Generated by Django 4.2.1 on 2023-06-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_occassion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='valid_till',
        ),
        migrations.AddField(
            model_name='coupons',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupons',
            name='minimum_price',
            field=models.BigIntegerField(default=4000),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='discount',
            field=models.IntegerField(default=100),
        ),
    ]
