# Generated by Django 4.2.1 on 2023-06-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_coupons_valid_till_coupons_is_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='discounted_price',
            field=models.BigIntegerField(default=3000),
        ),
    ]
