# Generated by Django 4.2.1 on 2023-06-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_variation_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='discounted_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
